replicaCount: 2

image:
  repository: nickfeld/ma_homework

resources:
  limits:
    memory: "128Mi"
    cpu: "500m"

deployment:
  portName: web
  containerPort: 8000

service:
  type: NodePort
  port: 80
  targetPort: web

ingress:
  host: arch.homework
  serviceName: ma-homework
  servicePortNumber: 80

postgresql:
  enabled: true
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  postgresqlDatabase: postgres
  postgresqlHost: "postgres"
  service:
    port: "5432"

# externalPostgresql:
#   postgresqlUsername: postgres
#   postgresqlPassword: postgres
#   postgresqlDatabase: postgres
#   postgresqlHost: "postgres"
#   postgresqlPort: "5432"