version: "3.9"
services:
  service:
    container_name: ma_homework_service
    image: nickfeld/ma_homework_01:0.1.0
    command: uvicorn app.webapp:app --host 0.0.0.0 --port 8000 --reload --reload-dir app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/homework